name: Ruby Gem

on:
  push:
    branches: [ "main" ]
    paths: [ "lib/version.rb", ".github/workflows/gem-push.yml" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "lib/version.rb", ".github/workflows/gem-push.yml" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.1
    - uses: rubygems/release-gem@v1
